In [87]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt



In [88]:
list1 = pd.read_csv('bank.csv', sep = ';' )
X = list1.iloc[:, [0,1,2,3,4,5,6,7]].values
y = list1.iloc[:, -1].values
# list1

list1.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [89]:
list1['job'].unique()  # 12 possible jobs 
list1.head()
list1['education'].unique()
list1['default'].unique()
list1['housing'].unique()
list1['y'].unique()

array(['no', 'yes'], dtype=object)

In [90]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

list1.head()
# the highest rank is 0, I will now rank the job from the normally most lucrative to the least lucrative
# Jobs
job = ['entrepreneur','management', 'admin.', 'self-employed', 'blue-collar', 'technician','services', 'retired', 'housemaid', 'student', 'unemployed', 'unknown']
enc_job = OrdinalEncoder(categories=[job])
list1[['job']] = enc_job.fit_transform(list1[['job']])

# Education
education = ['tertiary', 'secondary', 'primary', 'unknown' ]
enc_edu = OrdinalEncoder( categories = [education] )
list1[['education']]= enc_edu.fit_transform(list1[['education']])

# default    
default = ['yes', 'no']
enc_def = OrdinalEncoder( categories = [default] )
list1[['default']] = enc_def.fit_transform(list1[['default']])

# Housing
housing = ['yes', 'no']
enc_def = OrdinalEncoder( categories = [default] )    # All the yes and no values shall use enc_def 
list1['housing'] = enc_def.fit_transform(list1[['housing']])

# Loan
loan = ['yes', 'no']
enc_def = OrdinalEncoder( categories = [default] )
list1['loan'] = enc_def.fit_transform(list1[['loan']])

# y (the dependent variable)
y = ['yes', 'no']
enc_def = OrdinalEncoder( categories = [default] )
list1['y'] = enc.fit_transform(list1[['y']])

# Marital 
marital = ['married', 'single', 'divorced']
enc_mar = OrdinalEncoder( categories = [marital] )
list1['marital'] = enc_mar.fit_transform(list1[['marital']])
list1.head()


X = list1.iloc[:, [0,1,2,3,4,5,6,7]].values
y = list1.iloc[:, -1].values



array([[0., 2.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [91]:
#splitting into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [92]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [93]:
# Using KNeighbors Classifier 

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [94]:
y_pred = classifier.predict(X_test)
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1189    1]
 [ 166    1]]


In [95]:
# Using Logistic Regression

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [96]:
# confusion matrix
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1190    0]
 [ 167    0]]


In [97]:
# applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies)
# the cv = 10 arguement means that the process should cross validate 10 times, the accuracies are printed, displayed in a list form
print(accuracies.mean()) 
# mean of accuracies
print(accuracies.std())
# standard deviation of accuracies

[0.88643533 0.88643533 0.88643533 0.88643533 0.88924051 0.88924051
 0.88924051 0.88924051 0.88924051 0.88924051]
0.888118436289582
0.0013742495262589439


In [98]:
# Using Support Vector Machine

from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
#gaussian kernel used here
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [99]:
y_pred = classifier.predict(X_test)
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
y_predl = []
# for i in y_pred:
#     if i == 0:
#         y_predl.append('Yes')
#     if i ==1:
#         y_predl.append('No')
# print(y_predl)


[[1190    0]
 [ 167    0]]


In [100]:
# applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies)
# the cv = 10 arguement means that the process should cross validate 10 times, the accuracies are printed, displayed in a list form
print(accuracies.mean()) 
# mean of accuracies
print(accuracies.std())
# standard deviation of accuracies

[0.88643533 0.88643533 0.88643533 0.88643533 0.88924051 0.88924051
 0.88924051 0.88924051 0.88924051 0.88924051]
0.888118436289582
0.0013742495262589439


In [101]:
# Using XGBClassifier

from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [102]:
y_pred = classifier.predict(X_test)
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1162   28]
 [ 152   15]]
